Description: Headscale IPv6-centric EC2 stack
Parameters:
  HeadscaleRelease:
    Default: '0.23.0-alpha9'
    Description: 'Headscale release version to use: https://github.com/juanfont/headscale/releases'
    Type: String
  HostedZoneId:
    Description: Hosted Zone ID for the Headscale endpoint record.
    Type: String
  NextDnsId:
    Description: NextDNS account to be used with Headscale
    Type: String
  StackName:
    Default: headscale
    Description: Base name for resources. Meant to be headscale, changing can be useful for multiple stacks
    Type: String
Resources:
  AAAARecord:
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Join
        - ''
        - - !Ref 'StackName'
          - .
          - !GetAtt 'TriggerSSMLambdaCustomResource.DomainName'
      ResourceRecords:
        - !GetAtt 'DNSLambdaInvocation.Ipv6Address'
      TTL: '30'
      Type: AAAA
    Type: AWS::Route53::RecordSet
  DNSLambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
              - Action:
                  - ec2:DescribeInstances
                  - route53:ListHostedZones
                  - route53:GetHostedZone
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: LambdaEC2DescribeInstancesPolicy
    Type: AWS::IAM::Role
  DNSLambdaFunction:
    DependsOn:
      - EC2Instance
    Properties:
      Code:
        ZipFile: "import boto3\nimport cfnresponse\n\ndef lambda_handler(event, context):\n    ec2_client = boto3.client('ec2')\n    \n    try:\n        if event['RequestType'] in ['Create', 'Update']:\n\
          \            instance_id = event['ResourceProperties']['InstanceId']\n            response = ec2_client.describe_instances(InstanceIds=[instance_id])\n            \n            ipv6_addresses\
          \ = response['Reservations'][0]['Instances'][0]['NetworkInterfaces'][0]['Ipv6Addresses']\n            if not ipv6_addresses:\n                raise ValueError(\"No IPv6 address found for the instance.\"\
          )\n            \n            ipv6_address = ipv6_addresses[0]['Ipv6Address']\n            responseData = {'Ipv6Address': ipv6_address}\n            cfnresponse.send(event, context, cfnresponse.SUCCESS,\
          \ responseData)\n        \n        elif event['RequestType'] == 'Delete':\n            cfnresponse.send(event, context, cfnresponse.SUCCESS, {}, \"CustomResourcePhysicalID\")\n\n    except Exception\
          \ as e:\n        responseData = {'Message': str(e)}\n        cfnresponse.send(event, context, cfnresponse.FAILED, responseData, \"CustomResourcePhysicalID\")"
      Handler: index.lambda_handler
      Role: !GetAtt 'DNSLambdaExecutionRole.Arn'
      Runtime: python3.8
      Timeout: 10
    Type: AWS::Lambda::Function
  DNSLambdaInvocation:
    Properties:
      InstanceId: !Ref 'EC2Instance'
      ServiceToken: !GetAtt 'DNSLambdaFunction.Arn'
    Type: AWS::CloudFormation::CustomResource
  EC2Instance:
    Properties:
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      EbsOptimized: false
      IamInstanceProfile: !Ref 'InstanceProfile'
      ImageId: ami-08116b9957a259459
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          GroupSet:
            - !Ref 'HeadscaleSecurityGroup'
          SubnetId: !Ref 'HeadscalePublicSubnet'
      SourceDestCheck: true
      Tags:
        - Key: Name
          Value: headscale
      Tenancy: default
      UserData: !Base64
        Fn::Join:
          - ''
          - - "#!/bin/bash\n"
            - "apt update\n"
            - "apt install neovim -y\n"
            - "apt upgrade -y\n"
            - wget --output-document=headscale.deb https://github.com/juanfont/headscale/releases/download/v
            - !Ref 'HeadscaleRelease'
            - /headscale_
            - !Ref 'HeadscaleRelease'
            - "_linux_amd64.deb\n"
            - "apt install ./headscale.deb -y\n"
            - 'sed -i ''s#server_url: http://127.0.0.1:8080#server_url: https://'
            - !Ref 'StackName'
            - .
            - !GetAtt 'TriggerSSMLambdaCustomResource.DomainName'
            - "#' /etc/headscale/config.yaml\n"
            - "sed -i 's#listen_addr: 127.0.0.1:8080#listen_addr: 0.0.0.0:443#' /etc/headscale/config.yaml\n"
            - 'sed -i ''/acme_email:/s/.*/acme_email: "headscale@'
            - !GetAtt 'TriggerSSMLambdaCustomResource.DomainName'
            - "\"/' /etc/headscale/config.yaml\n"
            - 'sed -i ''/tls_letsencrypt_hostname:/s/.*/tls_letsencrypt_hostname: "'
            - !Ref 'StackName'
            - .
            - !GetAtt 'TriggerSSMLambdaCustomResource.DomainName'
            - "\"/' /etc/headscale/config.yaml\n"
            - "sed -i 's#tls_letsencrypt_challenge_type: HTTP-01#tls_letsencrypt_challenge_type: TLS-ALPN-01#' /etc/headscale/config.yaml\n"
            - 'sed -i ''s#base_domain: example.com#base_domain: '
            - !Ref 'StackName'
            - .
            - !GetAtt 'TriggerSSMLambdaCustomResource.DomainName'
            - "#' /etc/headscale/config.yaml\n"
            - "sed -i 's#nameservers:\n - 1.1.1.1#nameservers:\n - https://dns.nextdns.io/"
            - !Ref 'NextDnsId'
            - "#' /etc/headscale/config.yaml\n"
            - "systemctl enable headscale\n"
            - "reboot\n"
    Type: AWS::EC2::Instance
  HeadscaleInternetGateway:
    Properties:
      Tags:
        - Key: Name
          Value: headscale
    Type: AWS::EC2::InternetGateway
  HeadscalePublicSubnet:
    Properties:
      AssignIpv6AddressOnCreation: true
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      CidrBlock: 10.0.1.0/24
      Ipv6CidrBlock: !GetAtt 'TriggerSSMLambdaCustomResource.Ipv6CidrBlock'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: headscale-public
      VpcId: !Ref 'HeadscaleVpc'
    Type: AWS::EC2::Subnet
  HeadscaleRouteTable:
    Properties:
      Tags:
        - Key: Name
          Value: headscale
      VpcId: !Ref 'HeadscaleVpc'
    Type: AWS::EC2::RouteTable
  HeadscaleSecurityGroup:
    Properties:
      GroupDescription: Headscale EC2 Security Group
      SecurityGroupIngress:
        - CidrIpv6: ::/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      Tags:
        - Key: Name
          Value: headscale
      VpcId: !Ref 'HeadscaleVpc'
    Type: AWS::EC2::SecurityGroup
  HeadscaleSubnetRouteTableAssociation:
    Properties:
      RouteTableId: !Ref 'HeadscaleRouteTable'
      SubnetId: !Ref 'HeadscalePublicSubnet'
    Type: AWS::EC2::SubnetRouteTableAssociation
  HeadscaleVpc:
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: headscale
    Type: AWS::EC2::VPC
  HeadscaleVpcGatewayAttachment:
    Properties:
      InternetGatewayId: !Ref 'HeadscaleInternetGateway'
      VpcId: !Ref 'HeadscaleVpc'
    Type: AWS::EC2::VPCGatewayAttachment
  Headscaleipv6CidrBlock:
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref 'HeadscaleVpc'
    Type: AWS::EC2::VPCCidrBlock
  InstanceProfile:
    Properties:
      Roles:
        - !Ref 'SSMRoleForEC2'
    Type: AWS::IAM::InstanceProfile
  Ipv6CidrBlockSSM:
    Properties:
      Name: headscaleIPv6CidrBlock
      Type: String
      Value: The SSM parameter containing the Headscale VPC IPv6 CIDR block has not been set.
    Type: AWS::SSM::Parameter
  Ipv6Route:
    Properties:
      DestinationIpv6CidrBlock: ::/0
      GatewayId: !Ref 'HeadscaleInternetGateway'
      RouteTableId: !Ref 'HeadscaleRouteTable'
    Type: AWS::EC2::Route
  Route:
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'HeadscaleInternetGateway'
      RouteTableId: !Ref 'HeadscaleRouteTable'
    Type: AWS::EC2::Route
  SSMLambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ec2:DescribeIpv6Pools
                  - ec2:DescribeVpcs
                  - ssm:DeleteParameter
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: root
    Type: AWS::IAM::Role
  SSMLambdaFunction:
    Properties:
      Code:
        ZipFile: "import boto3\nimport cfnresponse\n\ndef lambda_handler(event, context):\n    ec2_client = boto3.client('ec2')\n    route53_client = boto3.client('route53')\n    ssm_client = boto3.client('ssm')\n\
          \    \n    try:\n        if event['RequestType'] in ['Create', 'Update']:\n            vpcs_response = ec2_client.describe_vpcs(Filters=[{\"Name\": \"tag:Name\", \"Values\": [\"headscale\"]}])\n\
          \            if not vpcs_response[\"Vpcs\"]:\n                raise ValueError(\"No VPC found with the name headscale\")\n\n            vpc_id = vpcs_response[\"Vpcs\"][0][\"VpcId\"]\n       \
          \     ipv6_cidr_block = vpcs_response[\"Vpcs\"][0][\"Ipv6CidrBlockAssociationSet\"][0][\"Ipv6CidrBlock\"]\n            ssm_client.put_parameter(\n                    Name=\"/config/headscale/ipv6CidrBlock\"\
          ,\n                    Value=ipv6_cidr_block,\n                    Type=\"String\",\n                    Overwrite=True\n                )\n\n            hosted_zone_id = event['ResourceProperties']['HostedZoneId']\n\
          \            hosted_zone = route53_client.get_hosted_zone(Id=hosted_zone_id)\n            domain_name = hosted_zone['HostedZone']['Name'].rstrip('.')\n            ssm_client.put_parameter(\n \
          \                   Name=\"/config/headscale/domainName\",\n                    Value=domain_name,\n                    Type=\"String\",\n                    Overwrite=True\n                )\n\
          \n            responseData = {'Ipv6CidrBlock': ipv6_cidr_block, 'DomainName': domain_name}\n            cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)\n        \n        elif\
          \ event['RequestType'] == 'Delete':\n            ssm_client.delete_parameter(Name=\"/config/headscale/ipv6CidrBlock\")\n            ssm_client.delete_parameter(Name=\"/config/headscale/domainName\"\
          )\n            cfnresponse.send(event, context, cfnresponse.SUCCESS, {}, \"CustomResourcePhysicalID\")\n\n    except Exception as e:\n        responseData = {'Message': str(e)}\n        cfnresponse.send(event,\
          \ context, cfnresponse.FAILED, responseData, \"CustomResourcePhysicalID\")\n"
      Handler: index.lambda_handler
      Role: !GetAtt 'SSMLambdaExecutionRole.Arn'
      Runtime: python3.8
      Timeout: 10
    Type: AWS::Lambda::Function
  SSMRoleForEC2:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonSSMPatchAssociation
    Type: AWS::IAM::Role
  TriggerSSMLambdaCustomResource:
    DependsOn:
      - Ipv6CidrBlockSSM
    Properties:
      ServiceToken: !GetAtt 'SSMLambdaFunction.Arn'
    Type: AWS::CloudFormation::CustomResource
